thesofproject/kconfig

kconfig-hda.sh
kconfig-sof-default.sh
kconfig-sof-nocodec.sh
kconfig-sst.sh

We can attach any debug kconfig or board specific defconfig with the
scripts.
EG: ../kconfig/kconfig-sof-default.sh ../kconfig/debug-defconfig
Signed-off-by: Pan Xiuli <xiuli.pan@linux.intel.com>

scripts: add attached options for kconfig

---

base-defconfig

Enable I2C_HID to enable touchpad mouse. Used on a lot of
laptops.
Signed-off-by: Kai Vehmanen <kai.vehmanen@linux.intel.com>

base-defconfig: add I2C_HID as module to enable touchpad

---

kconfig-sof-default.sh

Add pmc_core debugfs to default kernel config
for wake on voice pipeline test.
Signed-off-by: Amery Song <chao.song@intel.com>

kconfig: enable pmc_core debugfs in default kernel

---

base-defconfig

This option seems to wreck the SOF driver handling of ALSA controls.

base-config: add ALSA control checks

---

base-defconfig

No need to manually preserve .config files to check what changed
recently.
This is especially useful when .config is generated from fragments and
has to be moved around because these generation scripts do not support
out of tree O= builds.
As a module it uses no resource unless requested, so I can't find any
drawback.

base-defconfig: enable /proc/config.gz as a module

---

base-defconfig

This is required to configure it with module options.

base-defconfig: build netconsole as module

---

kconfig-sof-nocodec.sh

This patch is required to run the nocodec mode on SoundWire platforms.

kconfig-sof-codec: add soundwire detection

---

kconfig-sof-nocodec.sh

Reverts thesofproject/kconfig#56
This leads to issues on multiple fronts.

Revert "kconfig-sof-codec: add soundwire detection"

---

base-defconfig

The Fedora installer uses DM thin provisioning and XFS by default for
some Fedora flavors.
Default udev rules in Fedora have ATTR{queue/scheduler}="bfq" for eMMC
devices in file '60-block-scheduler.rules'.

base-defconfig: add three options required to boot some Fedora spins 

---

base-defconfig

We will need to figure out why PREEMPT_VOLUNTARY is not working, for
now stick to the same behavior as in previous releases
BugLink: https://github.com/thesofproject/linux/issues/3283

base-defconfig: select PREEMPT as work-around for 5.16-rc1 changes

---

base-defconfig

We don't care about Ubuntu snaps but we don't want a "degraded"
systemctl state to hide other systemctl issues. Enabling this will let
us add a systemctl check in verify-kernel-boot-log, see demo in
thesofproject/sof-test/pull/825 and thesofproject/sof-test/pull/827

base-defconfig: add SQUASHFS to fix systemctl "degraded" state

---

base-defconfig

Some TigerLake laptops need support for I2C_HID for the touchpad to
work. Blind bisection with other configurations helped identify the
options, I am not sure all of them are needed but that's already good
enough.

base-defconfig: add support for I2C_HID/ISH

---

kconfig-distro-sof-dev-update.sh
kconfig-distro-sof-update.sh
kconfig-hda.sh
kconfig-minimize-distro-add-sof-defaults.sh
kconfig-sof-arm64.sh
kconfig-sof-default.sh
kconfig-sof-nocodec.sh

To enable SOF on a platform, it may be easier to start from the
existing distro configurations.
kconfig-distro-sof-update.sh adds the minimal SOF options needed
kconfig-distro-sof-dev-update.sh: adds the SOF developer options
Most users would need the first script only.

kconfig: add two scripts to update distro config to sof and sof-dev

---

base-defconfig

Upstream commit [v5.17-rc2-4111-g410ce3dd5055](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=v5.17-rc2-4111-g410ce3dd5055) changed the default values
of CONFIG_HYPERVISOR_GUEST, CONFIG_PARAVIRT, CONFIG_KVM_GUEST,
CONFIG_PTP_1588_CLOCK_KVM and a couple hundreds others
410ce3dd5055b x86/config: Make the x86 defconfigs a bit more usable
We probably don't care about the new error message `kernel: fail to
initialize ptp_kvm` from CONFIG_PTP_1588_CLOCK_KVM but I think we do
care about all the others, notably:
```
config PARAVIRT
bool "Enable paravirtualization code"
depends on HAVE_STATIC_CALL
help
This changes the kernel so it can modify itself when it is run
under a hypervisor, potentially improving performance significantly
over full virtualization.  However, …
```

Disable CONFIG_HYPERVISOR_GUEST to revert new upstream default

---

base-defconfig

When graphics fail, a blank screen is not useful.
Even when graphics work, without a framebuffer console chvt still
works but it is "blind" / with a frozen GUI instead! Incredibly
confusing. Linux distributions expect this.
Also useful in case of hangs like
https://github.com/thesofproject/linux/issues/3387: text consoles
are always more responsive and they may even have some logs

base-config: add FRAMEBUFFER_CONSOLE

---

base-defconfig

This module can be used on UP Xtreme board to
monitor core temperature, enable it to reduce
the onboard fan noise.
Signed-off-by: Chao Song <chao.song@linux.intel.com>
After enable the kernel kconfig, use the utility here for fan speed auto-control: https://downloads.up-community.org/download/upx-tgl01-fan-control-linux/

base-defconfig: enable coretemp sensor driver

---

base-defconfig

These common Intel Ethernet interfaces are built-in by default in
`x86_64_defconfig`:
```
CONFIG_E100=y
CONFIG_E1000=y
CONFIG_E1000E=y
```
Maybe because we often use pre-production hardware, our kernel logs
and test results keep getting polluted by scary error messages like
`e1000e 0000:00:1f.6 eno1: Hardware Error` even when we don't use these
interfaces but a USB dongle instead.
Make these drivers modular so they can blocklisted when we don't use
them. As we never try to boot from the network so this should not
change anything for systems that do use these drivers and do not try
to block them.

Switch Intel E100* Ethernet drivers from built-in to modules

---

base-defconfig

Some Intel systems circa 2022 and later are locked into x2APIC mode and can not fall back to the legacy APIC modes if SGX or TDX are enabled in the BIOS.

base-defconfig: add X86_X2APIC

---

hdaudio-codecs-defconfig

Enable CONFIG_SND_HDA_INTEL_HDMI_SILENT_STREAM by default for HDMI code.
Signed-off-by: Kai Vehmanen <kai.vehmanen@linux.intel.com>

hdaudio-codecs-defconfig: enable silent-streaming for HDMI codec

---

base-defconfig

This is the EFI frame buffer device driver, the UEFI firmware version on our platforms is UEFI 2.0. We need to enable it for using the EFI framebuffer as console. This can solve the no graphics issue on MTL platform under nomodeset mode.
Signed-off-by: Keqiao Zhang <keqiao.zhang@intel.com>

base-defconfig: add CONFIG_FB_EFI

---

.github/workflows/buildtest.yml
kconfig-sof-nocodec.sh

This is a major difference with the 'default' configuration, and as a result of not having the PMC core enabled we infer the wrong conclusions.
The difference with the 'default' configuration should only be related to HDAudio and SoundWire removed.

kconfig-sof-nocodec: add telemetry-debugfs

---

sof-dev-defconfig

As no one ever wanted to boot from a microphone, it's very rare that we have to use the serial console to debug very early boot issues. But it can happen, see for instance
- https://github.com/thesofproject/linux/pull/4799
In such case it's very convenient to use another test device to collect logs on the serial console.

sof-dev-config: add CONFIG_USB_SERIAL_CP210X=m

---

soundwire-codecs-defconfig

Force compilation of the library, required until a codec selects it.

soundwire-codecs-defconfig: add SDCA library

---

base-defconfig

New driver: new, 6.10 error on cml-hel-rt5682.
```
kernel: acpi-fan INT3404:00: probe with driver acpi-fan failed with error -22
```
Easily avoided by blocklisting fan.ko on this model.
Part of the fix for:
- https://github.com/thesofproject/sof-test/issues/1198

base-defconfig: make ACPI_FAN / fan.ko a module so we can blocklist it

---

kconfig-sof-default.sh

For some reason the Intel CI uses an extra config required by the sof-test xrun_injection tests.
Make sure developers and CI rely on the same .config.

kconfig-sof-default: use xrun-debug by default
